# Mysql
# demo DB name
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Forex?userSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz@WSX
# Hibernate
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MYSQL
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.dialect.storage_engine: innodb
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging.level.org.hibernate:
  SQL: DEBUG
  type: TRACE